import { ScaledSheet, verticalScale, scale, moderateScale  } from "react-native-size-matters";

export const s = ScaledSheet.create({
  heroWrap: {
    marginTop: verticalScale(20),
  },
  pretitle: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: scale(12),
    lineHeight: verticalScale(19.2),
    letterSpacing: -0.03,
    color: "#616161",
  },
  title: {
    paddingTop: moderateScale(10),
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: scale(30),
    lineHeight: verticalScale(30),
    letterSpacing: -0.03,
    color: "#1D1D1D",
    marginTop: verticalScale(20),
  },
  bgImg: {
    width: "100%",
    height: undefined,
    aspectRatio: 2,
    marginTop: verticalScale(10),
    borderRadius: scale(10),
  },
  description: {
    fontFamily: "Source Sans",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: scale(16),
    lineHeight: verticalScale(21),
    letterSpacing: -0.03,
    color: "#000000",
    marginTop: verticalScale(20),
  },
  data: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: scale(12),
    lineHeight: verticalScale(19),
    color: "#6F7070",
    flexDirection: "row", 
    marginTop: verticalScale(8),
    display: "flex", 
    alignItems: 'center',
  },
  dataSource: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: scale(14),
    lineHeight: verticalScale(16),
    color: "#434a4a",
  },
});
